<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectContentforplaybackfromallcontentslisted</name>
   <tag></tag>
   <elementGuidId>dc161621-d198-49e5-b2e7-7a8d9f5fa3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@class='thumbnail-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@class='thumbnail-image']</value>
   </webElementProperties>
</WebElementEntity>
