<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pausecontentwhileplaying</name>
   <tag></tag>
   <elementGuidId>e3c16891-f03a-4563-88ea-9eb034a7c8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;playerInfoSection&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;playerInfoSection&quot;]</value>
   </webElementProperties>
</WebElementEntity>
